set(CMAKE_BUILD_TYPE "RelWithDebInfo" CACHE STRING "Build type (Debug, Release, etc.)")
set(CMAKE_CXX_FLAGS "-march=native -mfma -mavx -mavx2 -msse4 -fno-math-errno -DXSIMD_DEFAULT_ARCH='fma3<avx2>'" CACHE STRING "Recommended compiler flags")
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -g -DNDEBUG -ffast-math" CACHE STRING "Recommended compiler flags for a Release build")
set(BLAST_WITH_TEST ON CACHE BOOL "Build blast tests")
set(BLAST_WITH_BENCHMARK ON CACHE BOOL "Build blast benchmarks")
set(BLAST_WITH_BLASFEO ON CACHE BOOL "Build blasfeo C++ interface")
set(BLAST_BUILD_BLAST_BENCHMARK ON CACHE BOOL "Build BLAST benchmark")
set(BLAST_BUILD_LIBXSMM_BENCHMARK ON CACHE BOOL "Build LIBXSMM benchmark")
set(BLAST_BUILD_BLAS_BENCHMARK ON CACHE BOOL "Build benchmarks for all installed BLAS libraries")
set(BLAST_BUILD_BLAZE_BENCHMARK ON CACHE BOOL "Build Blaze benchmark")
set(BLAST_BUILD_EIGEN_BENCHMARK ON CACHE BOOL "Build Eigen benchmark")
set(BLAST_BUILD_BLASFEO_BENCHMARK ON CACHE BOOL "Build BLASFEO benchmark")
